Repository Sikdorang/Sikdorang, pull requests merged in 2025-07, with the labels that each got.

#29 feat: 가게 정보 불러오기
  apps/backend/src/auth/auth.module.ts
  apps/backend/src/auth/decorators/user-id.decorator.ts
  apps/backend/src/auth/utils/user.utils.ts
  apps/backend/src/store/store.controller.ts
  apps/backend/src/store/store.service.ts
  apps/backend/src/store/swagger/create-store.swagger.ts
  apps/backend/src/store/swagger/get-store.swagger.ts
Labels: feature

#37 @coderabbitai
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix

#39 Feat(fe-mv): 장바구니 기능에 메뉴 옵션 편집 및 선택 추가하기
  apps/frontend-menu-viewer/src/assets/icons/ic_cancel.svg
  apps/frontend-menu-viewer/src/assets/icons/ic_check_thin.svg
  apps/frontend-menu-viewer/src/components/common/CheckBox.tsx
  apps/frontend-menu-viewer/src/components/common/Header.tsx
  apps/frontend-menu-viewer/src/components/common/MinMaxText.tsx
  apps/frontend-menu-viewer/src/components/pages/Cart/OptionDropDown.tsx
  apps/frontend-menu-viewer/src/components/pages/Cart/OptionSelectorSheet.tsx
  apps/frontend-menu-viewer/src/components/pages/MenuDetail/OptionGroup.tsx
  apps/frontend-menu-viewer/src/components/pages/MenuDetail/OptionSelector.tsx
  apps/frontend-menu-viewer/src/index.css
  apps/frontend-menu-viewer/src/pages/Cart.tsx
  apps/frontend-menu-viewer/src/pages/Home.tsx
  apps/frontend-menu-viewer/src/pages/MenuDetail.tsx
  apps/frontend-menu-viewer/src/stores/useCartStore.ts
  apps/frontend-menu-viewer/src/stores/useMenuSelectionStore.ts
  apps/frontend-menu-viewer/src/types/global.d.ts
  apps/frontend-menu-viewer/src/utilities/isAllRequiredSelected.ts
Labels: feature, fe-menu-viewer, ai-review

#45 fix(fe-mv): 간단한 에러 수정
  apps/frontend-menu-viewer/src/components/pages/MenuDetail/MenuSection.tsx
  apps/frontend-menu-viewer/src/components/pages/Store/StoreInfoSection.tsx
  apps/frontend-menu-viewer/src/components/pages/Store/StoreMenuSection.tsx
  apps/frontend-menu-viewer/src/pages/MenuDetail.tsx
  apps/frontend-menu-viewer/src/pages/Store.tsx
  apps/frontend-menu-viewer/src/utilities/format.ts
Labels: bug, fix, fe-menu-viewer

#46 feat(fe-admin): 갤러리 형 메뉴 관리 구현
  apps/frontend-admin/package.json
  apps/frontend-admin/public/icons/ic_bottle.svg
  apps/frontend-admin/public/icons/ic_clock.svg
  apps/frontend-admin/public/icons/ic_info.svg
  apps/frontend-admin/public/icons/ic_naver.svg
  apps/frontend-admin/public/icons/ic_phone.svg
  apps/frontend-admin/public/icons/ic_toilet.svg
  apps/frontend-admin/public/icons/ic_wifi.svg
  apps/frontend-admin/src/app/(w-layout)/menu/category/page.tsx
  apps/frontend-admin/src/app/(w-layout)/menu/edit/[id]/page.tsx
  apps/frontend-admin/src/app/(w-layout)/menu/edit/page.tsx
  apps/frontend-admin/src/app/(w-layout)/shop/page.tsx
  apps/frontend-admin/src/components/common/inputs/ImageInput.tsx
  apps/frontend-admin/src/components/common/inputs/OptionInput.tsx
  apps/frontend-admin/src/components/common/inputs/TextInput.tsx
  apps/frontend-admin/src/components/common/loading/ErrorAnimation.tsx
  apps/frontend-admin/src/components/common/loading/Loading.tsx
  apps/frontend-admin/src/components/common/modals/EditModal.tsx
  apps/frontend-admin/src/components/common/modals/TooltipModal.tsx
  apps/frontend-admin/src/components/common/modals/TooltipModalPresenter.tsx
  apps/frontend-admin/src/components/layout/headers/NavigationBar.tsx
  apps/frontend-admin/src/components/layout/siders/NavigationBar.tsx
  apps/frontend-admin/src/components/pages/menuEdit/MenuCustomDropdown.tsx
  apps/frontend-admin/src/components/pages/menuEdit/MenuCustomDropdownItem.tsx
  apps/frontend-admin/src/components/pages/menuEdit/MenuCustomLabel.tsx
  apps/frontend-admin/src/components/pages/menuEdit/MenuGalleryCard.tsx
  apps/frontend-admin/src/components/pages/shop/ShopGuide.tsx
  apps/frontend-admin/src/components/pages/shop/ShopGuideItem.tsx
  apps/frontend-admin/src/contexts/EditModalContext.tsx
  apps/frontend-admin/src/hooks/useTooltipModal.ts
  apps/frontend-admin/src/styles/animations/dorang_crush.json
  apps/frontend-admin/src/styles/animations/dorang_defeat.json
  apps/frontend-admin/src/styles/animations/dorang_error.json
  apps/frontend-admin/src/styles/animations/dorang_loading.json
  apps/frontend-admin/src/styles/animations/dorang_walking.json
  apps/frontend-admin/src/types/model/menu.ts
  apps/frontend-admin/src/types/request/modal.ts
  pnpm-lock.yaml
Labels: fe-admin

#50 fix(be): 로그인과 인증 기능을 만듭니다.
  apps/backend/.env.docker
  apps/backend/.env.kakao
  apps/backend/.gitignore
  apps/backend/prisma/migrations/20250708215204_init/migration.sql
  apps/backend/prisma/migrations/20250708215422_change_kakaoid_to_bigint/migration.sql
  apps/backend/prisma/migrations/20250708220923_init/migration.sql
  apps/backend/prisma/migrations/20250712091229_change_store/migration.sql
  apps/backend/prisma/migrations/20250721111129_init/migration.sql
  apps/backend/prisma/schema.prisma
  apps/backend/src/app.module.ts
  apps/backend/src/auth/admin/admin-auth.controller.ts
  apps/backend/src/auth/admin/admin-auth.service.ts
  apps/backend/src/auth/admin/swagger/kakao-redirect.swagger.ts
  apps/backend/src/auth/admin/swagger/logout.swagger.ts
  apps/backend/src/auth/admin/swagger/refresh-access-token.swagger.ts
  apps/backend/src/auth/auth.module.ts
  apps/backend/src/auth/decorators/auth-ids.decorator.ts
  apps/backend/src/auth/guards/jwt-auth.guard.ts
  apps/backend/src/auth/userMobile/swagger/get-mobile-token.swagger.ts
  apps/backend/src/auth/userMobile/userMobile-auth.controller.ts
  apps/backend/src/auth/userMobile/userMobile-auth.service.ts
  apps/backend/src/auth/userTablet/swagger/logout.swagger.ts
  apps/backend/src/auth/userTablet/swagger/verify-pin.swagger.ts
  apps/backend/src/auth/userTablet/userTablet-auth.controller.ts
  apps/backend/src/auth/userTablet/userTablet-auth.service.ts
  apps/backend/src/auth/utils/user.utils.ts
  apps/backend/src/category/category.controller.ts
  apps/backend/src/category/category.module.ts
  apps/backend/src/category/category.service.ts
  apps/backend/src/category/dto/create-category.dto.ts
  apps/backend/src/category/swagger/create-category.swagger.ts
  apps/backend/src/category/swagger/get-category.swagger.ts
  apps/backend/src/main.ts
  apps/backend/src/store/dto/create-store.dto.ts
  apps/backend/src/store/store.controller.ts
  apps/backend/src/store/store.service.ts
Labels: feature

#56 feat(be): 메뉴 생성
  apps/backend/prisma/schema.prisma
  apps/backend/src/category/category.service.ts
  apps/backend/src/menu/dto/create-menu.dto.ts
  apps/backend/src/menu/menu.controller.ts
  apps/backend/src/menu/menu.service.ts
  apps/backend/src/menu/swagger/create-menu.swagger.ts
  apps/backend/src/store/store.service.ts
Labels: feature
