Repository Sikdorang/Sikdorang, pull requests merged in 2025-05, with the labels that each got.

#71 feat: update description and s3
  apps/be/docs/docs.go
  apps/be/docs/swagger.json
  apps/be/docs/swagger.yaml
  apps/be/go.mod
  apps/be/internal/menu/controller/menu.controller.go
  apps/be/internal/menu/dto/image_upload_target_response.dto.go
  apps/be/internal/menu/dto/update_description_request.dto.go
  apps/be/internal/menu/repository/menu.repository.go
  apps/be/internal/menu/service/menu.service.go
  apps/be/internal/models/image.go
  apps/be/internal/routes/category.go
  apps/be/internal/routes/index.go
  apps/be/internal/s3/controller/s3.controller.go
  apps/be/internal/s3/dto/generate_presignedURL_request.dto.go
  apps/be/internal/s3/repository/s3.repository.go
  apps/be/internal/s3/route/s3.route.go
  apps/be/internal/s3/service/s3.service.go
Labels: Feature

#73 feat: update order
  apps/be/docs/docs.go
  apps/be/docs/swagger.json
  apps/be/docs/swagger.yaml
  apps/be/internal/auth/service/auth.service.go
  apps/be/internal/category/controller/category.controller.go
  apps/be/internal/category/dto/update_category_order_request.dto.go
  apps/be/internal/category/repository/category.repository.go
  apps/be/internal/category/route/category.route.go
  apps/be/internal/category/service/category.service.go
  apps/be/internal/menu/controller/menu.controller.go
  apps/be/internal/menu/dto/update_description_request.dto.go
  apps/be/internal/menu/dto/update_menu_order.dto.go
  apps/be/internal/menu/repository/menu.repository.go
  apps/be/internal/menu/route/menu.route.go
  apps/be/internal/menu/service/menu.service.go
  apps/be/internal/middleware/jwt.go
  apps/be/internal/routes/index.go
  apps/be/internal/s3/controller/s3.controller.go
  apps/be/internal/s3/repository/s3.repository.go
  apps/be/internal/s3/route/s3.route.go
  apps/be/internal/utils/image.go
  apps/be/internal/utils/tag.go
  apps/be/main.go
Labels: Feature

#76 feat: get admin board
  apps/be/docs/docs.go
  apps/be/docs/swagger.json
  apps/be/docs/swagger.yaml
  apps/be/internal/menu/controller/menu.controller.go
  apps/be/internal/menu/dto/get_admin_menu_board_response.dto.go
  apps/be/internal/menu/repository/menu.repository.go
  apps/be/internal/menu/route/menu.route.go
  apps/be/internal/menu/service/menu.service.go
Labels: Feature

#77 fix: get description
  apps/be/internal/menu/dto/get_description_response.dto.go
  apps/be/internal/menu/service/menu.service.go
Labels: Fix

#78 Feat(fe)/menu board
  apps/be/internal/menu/dto/get_admin_menu_board_response.dto.go
  apps/fe/src/app/edit/page.tsx
  apps/fe/src/app/page.tsx
  apps/fe/src/app/preview/@modal/(.)[id]/page.tsx
  apps/fe/src/app/preview/[id]/page.tsx
  apps/fe/src/components/common/items/CategoryItem.tsx
  apps/fe/src/components/common/items/MenuItem.tsx
  apps/fe/src/components/common/items/MenuItemSkeleton.tsx
  apps/fe/src/components/layout/containers/SidebarWithContentContainer.tsx
  apps/fe/src/components/pages/edit/EditSaveButton.tsx
  apps/fe/src/components/pages/edit/SortableCategoryItem.tsx
  apps/fe/src/components/pages/edit/SortableCategoryList.tsx
  apps/fe/src/components/pages/edit/SortableMenuItem.tsx
  apps/fe/src/components/pages/edit/SortableMenuList.tsx
  apps/fe/src/components/pages/preview/Carousel.tsx
  apps/fe/src/components/pages/preview/CategorySidebar.tsx
  apps/fe/src/components/pages/preview/MenuList.tsx
  apps/fe/src/components/pages/preview/MenuModal.tsx
  apps/fe/src/components/pages/preview/MenuSection.tsx
  apps/fe/src/constants/messages.ts
  apps/fe/src/constants/storage.ts
  apps/fe/src/hooks/useCarousel.ts
  apps/fe/src/hooks/useLogin.ts
  apps/fe/src/hooks/useManageMenu.ts
  apps/fe/src/hooks/useMenuStatesByCategory.ts
  apps/fe/src/hooks/useQueryCategoriesAndMenus.ts
  apps/fe/src/hooks/useQueryMenusByCategory.ts
  apps/fe/src/hooks/useSortableItems.ts
  apps/fe/src/middleware.ts
  apps/fe/src/services/auth.ts
  apps/fe/src/services/category.ts
  apps/fe/src/services/index.ts
  apps/fe/src/services/manageMenu.ts
  apps/fe/src/services/menu.ts
  apps/fe/src/services/server.ts
  apps/fe/src/stores/useMenuOrderStore.ts
  apps/fe/src/types/model/category.ts
  apps/fe/src/types/model/menu.ts
  apps/fe/src/types/model/payload.ts
Labels: Feature

#83 feat: details images crud api
  apps/be/go.mod
  apps/be/internal/menu/service/menu.service.go
  apps/fe/package-lock.json
  apps/fe/package.json
  apps/fe/src/app/menu/@modifyModal/modify/page.tsx
  apps/fe/src/app/menu/page.tsx
  apps/fe/src/components/pages/menu/MenuImageGallery.tsx
  apps/fe/src/constants/messages.ts
  apps/fe/src/hooks/useManageMenuDetails.ts
  apps/fe/src/services/manageMenuDetails.ts
  apps/fe/src/types/model/menu.ts
Labels: Feature, Fix

#87 fix: fix preview image
  apps/be/internal/menu/dto/get_admin_menu_board_response.dto.go
  apps/be/internal/menu/repository/menu.repository.go
  apps/be/internal/menu/service/menu.service.go
Labels: Fix

#89 fix: create category body
  apps/be/internal/category/controller/category.controller.go
  apps/be/internal/category/dto/create_category_request.dto.go
  apps/be/internal/category/dto/update_category_request.dto.go
  apps/be/internal/category/service/category.service.go
Labels: Fix

#91 fix: fix conditions of preview and details
  apps/be/internal/menu/dto/update_description_request.dto.go
  apps/be/internal/menu/service/menu.service.go
Labels: Fix

#93 fix: fix adminMenuItemDTO
  apps/be/internal/menu/dto/get_admin_menu_board_response.dto.go
  apps/be/internal/menu/service/menu.service.go
Labels: Fix

#96 fix(be)/fix admin menu item dto
  apps/be/internal/menu/dto/get_admin_menu_board_response.dto.go
  apps/be/internal/menu/service/menu.service.go
Labels: Fix

#98 fix: fix menu_mapper and category dto
  apps/be/internal/category/controller/category.controller.go
  apps/be/internal/category/dto/get_category_response.dto.go
  apps/be/internal/utils/menu_mapper.go
Labels: Fix

#100 hotfix: details image upload bug fix
  apps/fe/src/components/pages/menu/MenuImageGallery.tsx
  apps/fe/src/hooks/useManageMenuDetails.ts
Labels: Fix

#102 Fix(fe)/chore
  apps/fe/public/favicon.ico
  apps/fe/public/icons/favicon.ico
  apps/fe/public/icons/logo/android-launchericon-128-128.png
  apps/fe/public/icons/logo/android-launchericon-144-144.png
  apps/fe/public/icons/logo/android-launchericon-192-192.png
  apps/fe/public/icons/logo/android-launchericon-48-48.png
  apps/fe/public/icons/logo/android-launchericon-512-512.png
  apps/fe/public/icons/logo/android-launchericon-72-72.png
  apps/fe/public/icons/logo/android-launchericon-96-96.png
  apps/fe/src/app/edit/page.tsx
  apps/fe/src/app/layout.tsx
  apps/fe/src/app/manifest.ts
  apps/fe/src/components/pages/edit/EditSaveButton.tsx
  apps/fe/src/components/pages/preview/MenuModal.tsx
  apps/fe/src/hooks/useSortableItems.ts
  apps/fe/src/stores/useMenuOrderStore.ts
  apps/fe/src/styles/globals.css
Labels: Fix

#105 feat: delete menu
  apps/be/docs/docs.go
  apps/be/docs/swagger.json
  apps/be/docs/swagger.yaml
  apps/be/internal/auth/controller/auth.controller.go
  apps/be/internal/menu/controller/menu.controller.go
  apps/be/internal/menu/dto/get_admin_menu_board_response.dto.go
  apps/be/internal/menu/route/menu.route.go
  apps/be/internal/menu/service/menu.service.go
Labels: Feature

#108 fix: Deployment issues — PWA check, image rendering, and disable ID/PW
  apps/fe/src/app/manifest.ts
  apps/fe/src/app/mypage/page.tsx
  apps/fe/src/components/pages/menu/MenuImageGallery.tsx
  apps/fe/src/components/pages/preview/Carousel.tsx
  apps/fe/src/middleware.ts
Labels: Bug, Fix

#112 fix: block back in menuboard
  apps/fe/src/app/preview/page.tsx
  apps/fe/src/components/pages/preview/AdminButton.tsx
  apps/fe/src/components/pages/preview/AdminModal.tsx
Labels: Fix

#120 chore: create test file
  .github/workflows/fe-lint-build.yml
  .nvmrc
  apps/fe/package-lock.json
  apps/fe/package.json
  package.json
  pnpm-lock.yaml
Labels: Fix, Setting

#128 feat: sse 연결하기
  apps/be/internal/category/route/category.route.go
  apps/be/internal/category/service/category.service.go
  apps/be/internal/menu/route/menu.route.go
  apps/be/internal/menu/service/menu.service.go
  apps/be/internal/notification/controller/sse.controller.go
  apps/be/internal/notification/gateway/hub.go
  apps/be/internal/notification/route/notification.route.go
  apps/be/internal/notification/service/notification.service.go
  apps/be/internal/routes/index.go
Labels: Feature

#123 fix: add debouncing in s3 upload
  apps/fe/src/app/menu/@modifyModal/modify/page.tsx
Labels: Fix

#130 feat: websocket
  apps/be/go.mod
  apps/be/internal/category/route/category.route.go
  apps/be/internal/category/service/category.service.go
  apps/be/internal/menu/route/menu.route.go
  apps/be/internal/menu/service/menu.service.go
  apps/be/internal/middleware/jwt.go
  apps/be/internal/routes/index.go
  apps/be/internal/ws/controller/ws.controller.go
  apps/be/internal/ws/gateway/ws.hub.go
  apps/be/internal/ws/route/ws.route.go
  apps/be/main.go
Labels: Feature

#132 Chore(fe)/connect jira GitHub
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/jira-issue-template.yml
Labels: Setting

#138 Chore(fe)/connect jira GitHub
  .github/ISSUE_TEMPLATE/jira-issue-template.yml
  .github/workflows/create-jira-issue.yml
Labels: Setting
