Repository Sikdorang/Sikdorang, pull requests merged in 2025-04, with the labels that each got.

#37 feat: menu manage page
  apps/fe/public/icons/ic_check.svg
  apps/fe/src/app/menu/page.tsx
  apps/fe/src/components/common/buttons/BaseButton.tsx
  apps/fe/src/components/common/inputs/CheckboxInput.tsx
  apps/fe/src/components/common/labels/ProductTag.tsx
  apps/fe/src/components/pages/.gitkeep
  apps/fe/src/components/pages/menu/MainControlButton.tsx
  apps/fe/src/components/pages/menu/ManageButton.tsx
  apps/fe/src/components/pages/menu/MenuElementLabel.tsx
  apps/fe/src/components/pages/menu/MenuManageSelect.tsx
  apps/fe/src/styles/globals.css
  apps/fe/tsconfig.json
Labels: Feature

#38 feat: create login page(ui)
  apps/fe/public/fonts/Pretendard-Black.otf
  apps/fe/public/fonts/Pretendard-Bold.otf
  apps/fe/public/fonts/Pretendard-ExtraBold.otf
  apps/fe/public/fonts/Pretendard-ExtraLight.otf
  apps/fe/public/fonts/Pretendard-Light.otf
  apps/fe/public/fonts/Pretendard-Medium.otf
  apps/fe/public/fonts/Pretendard-Regular.otf
  apps/fe/public/fonts/Pretendard-SemiBold.otf
  apps/fe/public/fonts/Pretendard-Thin.otf
  apps/fe/public/fonts/PretendardVariable.woff2
  apps/fe/src/app/layout.tsx
  apps/fe/src/app/page.tsx
  apps/fe/src/components/layout/headers/TopNav.tsx
  apps/fe/src/components/pages/login/LinkButton.tsx
  apps/fe/src/components/pages/login/LoginForm.tsx
Labels: Feature, UI

#41 feat: setup swagger
  apps/be/docs/docs.go
  apps/be/docs/swagger.json
  apps/be/docs/swagger.yaml
  apps/be/go.mod
  apps/be/internal/auth/controller/auth.controller.go
  apps/be/internal/auth/dto/login_request.dto.go
  apps/be/internal/auth/dto/login_response.dto.go
  apps/be/internal/auth/dto/logout_response.dto.go
  apps/be/internal/auth/dto/refresh_token_response.dto.go
  apps/be/internal/category/controller/category.controller.go
  apps/be/internal/category/dto/create_category.dto.go
  apps/be/internal/category/dto/create_category_request.dto.go
  apps/be/internal/category/dto/create_category_response.dto.go
  apps/be/internal/category/dto/get_category_response.dto.go
  apps/be/internal/category/repository/category.repository.go
  apps/be/internal/category/service/category.service.go
  apps/be/internal/common/dto/error_response.dto.go
  apps/be/internal/routes/index.go
  apps/be/main.go
Labels: Feature

#44 Feat(fe)/login
  apps/fe/package-lock.json
  apps/fe/package.json
  apps/fe/src/app/layout.tsx
  apps/fe/src/components/common/buttons/BaseButton.tsx
  apps/fe/src/components/common/inputs/TextInput.tsx
  apps/fe/src/components/common/labels/ErrorMessage.tsx
  apps/fe/src/components/common/loadings/Spinner.tsx
  apps/fe/src/components/pages/login/LinkButton.tsx
  apps/fe/src/components/pages/login/LoginForm.tsx
  apps/fe/src/constants/messages.ts
  apps/fe/src/constants/storage.ts
  apps/fe/src/hooks/useLogin.ts
  apps/fe/src/providers/mswProvider.tsx
  apps/fe/src/providers/tanstackProvider.tsx
  apps/fe/src/providers/toastProvider.tsx
  apps/fe/src/services/auth.ts
  apps/fe/src/services/handleError.ts
  apps/fe/src/services/index.ts
  apps/fe/src/styles/globals.css
  apps/fe/src/utilities/validations.ts
Labels: Feature, Refactor

#46 Feat(be)/menu crud
  apps/be/docs/docs.go
  apps/be/docs/swagger.json
  apps/be/docs/swagger.yaml
  apps/be/internal/category/repository/category.repository.go
  apps/be/internal/category/service/category.service.go
  apps/be/internal/menu/controller/menu.controller.go
  apps/be/internal/menu/dto/get_menu_response.dto.go
  apps/be/internal/menu/dto/sync_menu_error.dto.go
  apps/be/internal/menu/dto/sync_menu_request.dto.go
  apps/be/internal/menu/repository/menu.repository.go
  apps/be/internal/menu/route/menu.route.go
  apps/be/internal/menu/service/menu.service.go
  apps/be/internal/models/menu.go
  apps/be/internal/routes/category.go
  apps/be/internal/routes/index.go
  apps/be/internal/utils/menu_mapper.go
Labels: Feature

#49 Fix: fix category read
  apps/be/internal/category/controller/category.controller.go
  apps/be/internal/category/dto/get_category_response.dto.go
Labels: Fix

#53 feat: menu Board and description
  apps/be/docs/docs.go
  apps/be/docs/swagger.json
  apps/be/docs/swagger.yaml
  apps/be/internal/category/controller/category.controller.go
  apps/be/internal/category/repository/category.repository.go
  apps/be/internal/menu/controller/menu.controller.go
  apps/be/internal/menu/dto/get_description_response.dto.go
  apps/be/internal/menu/dto/get_menu_board_response.dto.go
  apps/be/internal/menu/dto/get_menu_response.dto.go
  apps/be/internal/menu/repository/menu.repository.go
  apps/be/internal/menu/route/menu.route.go
  apps/be/internal/menu/service/menu.service.go
  apps/be/internal/models/category.go
  apps/be/internal/models/image.go
  apps/be/internal/models/menu.go
  apps/be/internal/models/tag.go
  apps/be/internal/utils/menu_mapper.go
Labels: Feature

#59 feat: update menu details
  apps/be/docs/docs.go
  apps/be/docs/swagger.json
  apps/be/docs/swagger.yaml
  apps/be/internal/auth/controller/auth.controller.go
  apps/be/internal/menu/controller/menu.controller.go
  apps/be/internal/menu/dto/update_description_request.dto.go
  apps/be/internal/menu/repository/menu.repository.go
  apps/be/internal/menu/route/menu.route.go
  apps/be/internal/menu/service/menu.service.go
  apps/be/internal/utils/image.go
  apps/be/internal/utils/tag.go
Labels: Feature

#64 chore: update to a build-error-free version for deployment
  apps/fe/package.json
  apps/fe/public/icons/ic_3_lines.svg
  apps/fe/src/app/menu/@modifyModal/modify/page.tsx
  apps/fe/src/app/menu/page.tsx
  apps/fe/src/components/common/.gitkeep
  apps/fe/src/components/common/labels/ProductTag.tsx
  apps/fe/src/components/layout/headers/TopNav.tsx
  apps/fe/src/components/layout/sidebars/CategorySidebar.tsx
  apps/fe/src/components/pages/menu/MenuHeader.tsx
  apps/fe/src/components/pages/menu/MenuImageGallery.tsx
  apps/fe/src/components/pages/menu/MenuTableElement.tsx
  apps/fe/src/components/pages/menu/cells/MainControlButton.tsx
  apps/fe/src/components/pages/menu/cells/ManageButton.tsx
  apps/fe/src/components/pages/menu/cells/MenuElementLabel.tsx
  apps/fe/src/components/pages/menu/cells/MenuManageSelect.tsx
  apps/fe/src/components/pages/menu/cells/MenuTextInput.tsx
  apps/fe/src/constants/enums.ts
  apps/fe/src/hooks/useManageCategory.ts
  apps/fe/src/hooks/useManageMenu.ts
  apps/fe/src/hooks/useManageMenuDetails.ts
  apps/fe/src/services/manageMenuDetails.ts
  apps/fe/src/styles/globals.css
  apps/fe/src/types/model/menu.ts
Labels: Feature, Refactor

#65 chore: fix build errors
  apps/fe/eslint.config.mjs
  apps/fe/src/app/menu/@modifyModal/modify/page.tsx
  apps/fe/src/app/menu/layout.tsx
  apps/fe/src/app/menu/page.tsx
  apps/fe/src/app/preview/[id]/page.tsx
  apps/fe/src/components/common/loadings/Spinner.tsx
  apps/fe/src/components/layout/headers/TopNav.tsx
  apps/fe/src/components/layout/sidebars/CategorySidebar.tsx
  apps/fe/src/components/pages/menu/MenuElementLabel.tsx
  apps/fe/src/components/pages/menu/MenuImageGallery.tsx
  apps/fe/src/components/pages/menu/MenuTableElement.tsx
  apps/fe/src/components/pages/menu/MenuTextInput.tsx
  apps/fe/src/components/pages/menu/cells/MenuElementLabel.tsx
  apps/fe/src/hooks/useManageCategory.ts
  apps/fe/src/hooks/useManageMenu.ts
  apps/fe/src/hooks/useManageMenuDetails.ts
  apps/fe/src/services/manageMenu.ts
  apps/fe/src/services/menu.ts
  apps/fe/src/types/model/menu.ts
Labels: Fix

#67 hotfix: circuler dependency error
  apps/be/go.mod
  apps/fe/src/hooks/useManageCategory.ts
  pnpm-lock.yaml
Labels: Fix

#69 hotfix: price update error in menu table
  apps/fe/src/app/menu/page.tsx
  apps/fe/src/components/pages/menu/MenuTableElement.tsx
  apps/fe/src/types/model/menu.ts
Labels: Bug, Fix
