Repository Sikdorang/Sikdorang, pull requests merged in 2025-08, with the labels that each got.

#62 feat(be): 메뉴 상세정보 업데이트
  apps/backend/src/category/category.service.ts
  apps/backend/src/menu/dto/create-menu.dto.ts
  apps/backend/src/menu/dto/update-menu-details.dto.ts
  apps/backend/src/menu/dto/update-menu.dto.ts
  apps/backend/src/menu/menu.controller.ts
  apps/backend/src/menu/menu.service.ts
  apps/backend/src/menu/swagger/create-menus.swagger.ts
  apps/backend/src/menu/swagger/update-menu-details.swagger.ts
  apps/backend/src/menu/swagger/update-menus.swagger.ts
Labels: feature

#66 fix: apps/frontend-user directory
  apps/frontend-user/next-env.d.ts
Labels: fix

#76 feat(be): 메뉴 상세정보 가져오기
  apps/backend/prisma/schema.prisma
  apps/backend/src/api/menu/menu.controller.ts
  apps/backend/src/api/menu/menu.service.ts
  apps/backend/src/api/menu/swagger/get-AllMenus.swagger.ts
  apps/backend/src/api/menu/swagger/get-menu-detail.swagger.ts
Labels: feature

#93 feat: 관리자 설정 UI 구현
  apps/backend/src/api/category/category.controller.ts
  apps/frontend-admin/public/icons/ic_circle_check.svg
  apps/frontend-admin/public/icons/ic_kakao_icon.png
  apps/frontend-admin/public/images/img_dorang_11.png
  apps/frontend-admin/public/images/img_example_qr.png
  apps/frontend-admin/public/images/img_kakao_qr.png
  apps/frontend-admin/public/images/img_qr_book.png
  apps/frontend-admin/public/sounds/bgm_sikdorang.mp3
  apps/frontend-admin/public/sounds/notification.mp3
  apps/frontend-admin/src/app/(w-layout)/dashboard/page.tsx
  apps/frontend-admin/src/app/(w-layout)/history/page.tsx
  apps/frontend-admin/src/app/(w-layout)/link/page.tsx
  apps/frontend-admin/src/app/(w-layout)/link/setting/page.tsx
  apps/frontend-admin/src/app/(w-layout)/menu/edit/page.tsx
  apps/frontend-admin/src/app/(w-layout)/order/page.tsx
  apps/frontend-admin/src/app/(w-layout)/preview/page.tsx
  apps/frontend-admin/src/app/(w-layout)/recommend/full/page.tsx
  apps/frontend-admin/src/app/(w-layout)/recommend/light/page.tsx
  apps/frontend-admin/src/app/(w-layout)/recommend/page.tsx
  apps/frontend-admin/src/app/(w-layout)/settings/page.tsx
  apps/frontend-admin/src/app/(w-layout)/settings/report/page.tsx
  apps/frontend-admin/src/app/(w-layout)/settings/reset/page.tsx
  apps/frontend-admin/src/app/(wo-layout)/page.tsx
  apps/frontend-admin/src/components/common/buttons/CtaButton.tsx
  apps/frontend-admin/src/components/common/buttons/SoundButton.tsx
  apps/frontend-admin/src/components/common/inputs/ImageInput.tsx
  apps/frontend-admin/src/components/common/modals/ConfirmModal.tsx
  apps/frontend-admin/src/components/common/modals/WarningModal.tsx
  apps/frontend-admin/src/components/layout/headers/NavigationBar.tsx
  apps/frontend-admin/src/components/layout/siders/NavigationBar.tsx
  apps/frontend-admin/src/components/pages/history/FilterBar.tsx
  apps/frontend-admin/src/components/pages/history/OrderDetail.tsx
  apps/frontend-admin/src/components/pages/history/OrderTable.tsx
  apps/frontend-admin/src/components/pages/link/QRLinkTableRow.tsx
  apps/frontend-admin/src/components/pages/login/PolicyModal.tsx
  apps/frontend-admin/src/components/pages/menuEdit/MenuCustomFinderDropdown.tsx
  apps/frontend-admin/src/components/pages/menuEdit/MenuTableRow.tsx
  apps/frontend-admin/src/components/pages/order/OrderListItem.tsx
  apps/frontend-admin/src/components/pages/recommend/RecommendTableRow.tsx
  apps/frontend-admin/src/components/pages/recommend/RepresentDrinkSelector.tsx
  apps/frontend-admin/src/components/pages/recommend/ThreeStepSlider.tsx
  apps/frontend-admin/src/components/pages/settings/KakaoChannelGuide.tsx
  apps/frontend-admin/src/components/pages/settings/SettingItem.tsx
  apps/frontend-admin/src/components/pages/settings/SettingTable.tsx
  apps/frontend-admin/src/components/pages/settings/SettingTableRow.tsx
  apps/frontend-admin/src/constants/messages.ts
  apps/frontend-admin/src/types/model/link.ts
  apps/frontend-admin/src/types/model/store.ts
  packages/tokens/src/colors.css
Labels: fe-admin
